merge lxc-0.8.0-rc2

diff --git a/lxc-destroy b/lxc-destroy
--- a/lxc-destroy
+++ b/lxc-destroy
@@ -26,7 +26,9 @@
 #
 
 usage() {
-    echo "usage: $0 -n <name>"
+    echo "usage: $0 -n <name> [-f] [-p <parent dir>]"
+    echo "  -f: if a container is running, stop it first.  Default is to abort"
+    echo "  -p: set container's parent directory"
 }
 
 if [ "$(id -u)" != "0" ]; then
@@ -34,9 +36,11 @@ if [ "$(id -u)" != "0" ]; then
    exit 1
 fi
 
-shortoptions='n:p:'
-longoptions='name:,path:'
-lxc_path=/usr/local/var/lib/lxc
+shortoptions='n:fp:'
+longoptions='name:,force,path:'
+localstatedir=/usr/local/var
+lxc_path=${localstatedir}/lib/lxc
+force=0
 
 getopt=$(getopt -o $shortoptions --longoptions  $longoptions -- "$@")
 if [ $? != 0 ]; then
@@ -48,24 +52,28 @@ eval set -- "$getopt"
 
 while true; do
         case "$1" in
-        -n|--name)
-        shift
-        lxc_name=$1
-        shift
-        ;;
-        -p|--path)
-        shift
-        lxc_path=$1
-        shift
-        ;;
+	    -n|--name)
+		shift
+		lxc_name=$1
+		shift
+		;;
+	    -p|--path)
+		shift
+		lxc_path=$1
+		shift
+		;;
+	    -f|--force)
+		force=1
+		shift
+		;;
             --)
-        shift
-        break;;
+		shift
+		break;;
             *)
-        echo $1
-        usage $0
-        exit 1
-        ;;
+		echo $1
+		usage $0
+		exit 1
+		;;
         esac
 done
 
@@ -80,15 +88,29 @@ if [ ! -d "$lxc_path/$lxc_name" ]; then
     exit 1
 fi
 
+# make sure the container isn't running
+lxc-info -n $lxc_name 2>/dev/null | grep -q RUNNING
+if [ $? -eq 0 ]; then
+	if [ $force -eq 1 ]; then
+		lxc-stop -n $lxc_name
+	else
+		echo "Container $lxc_name is running, aborting the deletion."
+		exit 1
+	fi
+fi
+
 # Deduce the type of rootfs
 # If LVM partition, destroy it.  If anything else, ignore it.  We'll support
 # deletion of others later.
-rootdev=`grep lxc.rootfs $lxc_path/$lxc_name/config | awk -F= '{ print $2 '}`
-if [ -b $rootdev -o -h $rootdev ]; then
-    lvdisplay $rootdev > /dev/null 2>&1
-    if [ $? -eq 0 ]; then
-        lvremove $rootdev
-    fi
+rootdev=`grep lxc.rootfs $lxc_path/$lxc_name/config 2>/dev/null | sed -e 's/^[^/]*/\//'`
+if [ ! -z "$rootdev" ]; then
+	if [ -b "$rootdev" -o -h "$rootdev" ]; then
+		lvdisplay $rootdev > /dev/null 2>&1
+		if [ $? -eq 0 ]; then
+			echo "removing backing store: $rootdev"
+			lvremove -f $rootdev
+		fi
+	fi
 fi
 # recursively remove the container to remove old container configuration
-rm -rf --preserve-root $lxc_path/$lxc_name
+rm -rf --one-file-system --preserve-root $lxc_path/$lxc_name
